 # For more - see https://help.github.com/articles/displaying-a-sponsor-button-in-your-repository

github: marcosguilhermef
custom: https://paypal.com/donate/?hosted_button_id=8G3MV5ZY4KYC2
pix: https://toolsfordevs.com.br/_next/image?url=%2Fpix.jpeg&w=256&q=75